server:
  port: 8080

spring:
  datasource:
    url: ###
    username: root
    password: "%6-rlyj!BESEGH"

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
