server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://43.142.159.129:3306/mail?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: "%6-rlyj!BESEGH"

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml